// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9y9FKg8M2EFrmgU8CHEdTj5tJbhujZeY',
    appId: '1:246928857627:web:003b70b36f534fc10176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    authDomain: 'fir-storge-de5cb.firebaseapp.com',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    measurementId: 'G-YT11L54C5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzn4d0grm4Blx-usQLMrsQU-IbFkZ33w',
    appId: '1:246928857627:android:e280582280b1f0480176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASReMjqQRT0zMvJ0g56hb0hHhLaKNkz9s',
    appId: '1:246928857627:web:f292204b5c4291ea0176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    authDomain: 'fir-storge-de5cb.firebaseapp.com',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    measurementId: 'G-1BW0WTX0YY',
  );
}
